# Generated by Django 6.0.3 on 2026-04-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_creditaccount_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
