# Generated by Django 6.0.3 on 2026-03-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
