# Generated by Django 6.0.3 on 2026-04-01 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('services', '0003_servicepartused_serviceworklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicepartused',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='serviceworklog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Technician commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='delivery_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('delivered', 'Delivered')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='device_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='device_imei',
            field=models.CharField(blank=True, help_text='IMEI or serial number', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='estimated_minutes',
            field=models.IntegerField(default=60, help_text='Estimated repair time in minutes'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('split', 'Split'), ('credit', 'Credit')], max_length=20),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='screen_condition',
            field=models.CharField(choices=[('ok', 'OK / Undamaged'), ('damaged', 'Screen Damaged'), ('cracked', 'Cracked'), ('missing', 'Screen Missing')], default='ok', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='screen_condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='file',
            field=models.FileField(upload_to='service_media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='issues',
            field=models.TextField(help_text='Comma-separated list of issues reported by customer'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('return', 'Return'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepartused',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Captured at time of use', max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceworklog',
            name='status_change',
            field=models.CharField(blank=True, help_text='If this log triggered a status change', max_length=20),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status', 'department'], name='services_se_status_c4c44f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['customer_phone'], name='services_se_custome_3f43f7_idx'),
        ),
    ]
