# Generated by Django 6.0.3 on 2026-04-01 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_options_alter_product_options_and_more'),
        ('services', '0004_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='device_appearance',
            field=models.TextField(blank=True, help_text='Screen look or device damages upon receipt'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='technician_comments_initial',
            field=models.TextField(blank=True, help_text='Initial comment for the technician'),
        ),
        migrations.AddField(
            model_name='servicepartused',
            name='part_name',
            field=models.CharField(blank=True, help_text='Required if source is vendor', max_length=200),
        ),
        migrations.AddField(
            model_name='servicepartused',
            name='source',
            field=models.CharField(choices=[('inventory', 'Internal Inventory'), ('vendor', 'External Vendor/Service')], default='inventory', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='servicepartused',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
