# Generated by Django 6.0.3 on 2026-04-09 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_technician_assignment_vendor_ledger'),
        ('services', '0005_serviceorder_device_appearance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, help_text='The technician responsible for this repair', limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_technical_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='technical_phase_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='technical_phase_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepartused',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor to pay when source is external', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_parts', to='inventory.vendor'),
        ),
    ]
