# Generated by Django 6.0.3 on 2026-04-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_technician_assignment_vendor_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemedia',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='servicepartused',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceworklog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
