# Generated by Django 6.0.3 on 2026-03-31 20:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.TenantUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Company Admin'), ('manager', 'Manager'), ('technician', 'Technician'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
    ]
