# Generated by Django 6.0.3 on 2026-04-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Company Admin'), ('manager', 'Manager'), ('technician', 'Technician'), ('cashier', 'Cashier'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'role'], name='accounts_us_company_8958d5_idx'),
        ),
    ]
