# Generated by Django 6.0.3 on 2026-05-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Company Admin'), ('manager', 'Manager'), ('hardware_technician', 'Hardware Technician'), ('software_technician', 'Software Technician'), ('cashier', 'Cashier'), ('staff', 'Staff')], default='staff', max_length=25),
        ),
    ]
