# Generated by Django 6.0.3 on 2026-04-01 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('inventory', '0002_product_cost_price_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand', 'model_name']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode/SKU for scanner input', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Staff commission per unit sold', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='issues',
            field=models.TextField(blank=True, help_text='Known issues or product description notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Alert when stock falls below this level'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retail sale price', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service/repair price charged to customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Invoice/PO/Service Order reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Purchase cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_capacity',
            field=models.CharField(blank=True, help_text='e.g. 128GB, 256GB', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model_name'], name='inventory_p_brand_727318_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'),
        ),
    ]
