# Generated by Django 6.0.3 on 2026-04-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_technician_assignment_vendor_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='balance',
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current amount owed to this vendor (total_purchases - total_paid)', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative amount paid back to this vendor', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative value of all parts/services ordered from vendor', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorledger',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Debit (Part/Service Ordered)'), ('CREDIT', 'Credit (Payment Made to Vendor)')], max_length=10),
        ),
    ]
