# Generated by Django 6.0.3 on 2026-04-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
