# Generated by Django 6.0.3 on 2026-04-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_customer_options_alter_possession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount of credit (purchases) issued', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid back by the customer', max_digits=12),
        ),
        migrations.AddField(
            model_name='customercreditledger',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='possession',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customercreditledger',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Debit (Purchase on Credit)'), ('CREDIT', 'Credit (Payment Received)')], max_length=20),
        ),
    ]
